[project]
name = "unity-mcp-server"
version = "0.1.0"
description = "MCP server for Unity Editor control"
requires-python = ">=3.11"
dependencies = [
    "mcp>=0.9.0",
    "httpx>=0.24.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

